[project]
name = "megaton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "cachetools>=7.1.4",
    "disnake>=2.12.0",
    "humanize>=4.15.0",
    "modern-colorthief>=0.3.0",
    "msgspec>=0.21.1",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39.7",
    "ruff>=0.15.17",
]
